name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install pnpm
        run: corepack enable && corepack prepare pnpm@latest --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint (fix)
        run: pnpm lint --fix

      - name: Type-check
        run: pnpm check-types || echo "TypeScript errors found but build continues due to ignoreBuildErrors setting"

      - name: Env sanity check
        run: node scripts/check-env.mjs || true
        # Do not fail CI for check-env in PRs if we don't have secrets, but print results.
        # Optionally, set required env secrets in workflow for production checks.

      - name: Build
        run: pnpm build
